[package]
name = "interlude-vk"
version = "0.1.0"
authors = ["S.Percentage <Syn.Tri.Naga@gmail.com>"]
description = "Interlude: Vulkan FFI And Objective Wrapping"

[features]
noimpl = []

[dependencies]
libc = "0.2.20"
